### ISSUE TITLE
Hide major version updates

### ISSUE THREAD

**Issue by rightaway** [mskelton/yarn-plugin-outdated#57] opened 2022-05-20 08:25 UTC
Can there be an option to hide major version updates? I have package.json files that set exact dependency versions and there are times I just want to do non breaking updates or when I'm stuck on old versions of packages because of breaking changes.

I'd like to hide the major updates and only see minor and patch updates. Now I have to check all the output and ignore the lines that are from major updates. Would be good to run this plugin with a `--hide-major` option and not see any packages when I'm all up to date with non breaking changes.

**Comment by mskelton** [comment] 2022-05-21 13:53
Possible duplicate of #45?

**Comment by rightaway** [comment] 2022-05-21 22:13
This is a duplicate of https://github.com/mskelton/yarn-plugin-outdated/issues/45#issuecomment-1046343891. If we could pass `--severity patch,minor` that would hide major versions.

But the main feature for that one is https://github.com/mskelton/yarn-plugin-outdated/issues/45#issuecomment-1046533234 so I created a separate issue.

**Closed** 2022-05-21 22:34 UTC

**Comment by rightaway** [comment] 2022-05-22 09:55
The error `Usage Error: Invalid value for --severity: expected a valid enumeration value (got "patch,major")` is gone but it's saying all my dependencies are up to date. When I don't include --severity there are patch and major versions that need to be updated.

**Comment by mskelton** [comment] 2022-05-22 20:17
You have to specify the flag multiple times.

```sh
yarn outdated --severity=patch --severity=minor
```

That said since most shells support brace expansion, you can do this.

```sh
yarn outdated --severity={patch,minor}
```

**Comment by rightaway** [comment] 2022-05-23 06:34
To be consistent with `--workspace` https://github.com/mskelton/yarn-plugin-outdated/issues/61 can the `=` become optional, and can it allow commas between severity types too?
